env: dev

image:
  repository: mattlangsenkamp/ingestion-server
  tag: latest
  pullPolicy: Always

serviceAccount:
  irsaRoleArn: arn:aws:iam::853236864732:role/ingestion-irsa-role-64321c2

replicaCount: 1
