env: dev

image:
  repository: mattlangsenkamp/ingestion-server
  tag: latest
  pullPolicy: Always

serviceAccount:
  irsaRoleArn: ""  # auto-populated by `make infra-up STACK=<env>`

replicaCount: 1
