apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  MESSAGING_MODE: {{ .Values.messagingMode | quote }}
  AWS_REGION: {{ .Values.awsRegion | quote }}
  STORAGE_ENV: {{ .Values.env | quote }}
  LUCENE_INDEX_PATH: {{ .Values.writerConfig.luceneIndexPath | quote }}
  BATCH_SIZE: {{ .Values.writerConfig.batchSize | quote }}
  FLUSH_THRESHOLD: {{ .Values.writerConfig.flushThreshold | quote }}
  COMMIT_THRESHOLD: {{ .Values.writerConfig.commitThreshold | quote }}
