// Generated by Mill 1.1.0-RC3
package build_

@_root_.scala.annotation.nowarn
object MillMiscInfo
    extends mill.api.internal.RootModule.Info(
  projectRoot0 = "/home/mattlang/Documents/projects/zio-lucene-test",
  output0 = "/home/mattlang/Documents/projects/zio-lucene-test/.bsp/mill-bsp-out",
  topLevelProjectRoot0 = "/home/mattlang/Documents/projects/zio-lucene-test"
)

