apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
  data:
    # S3 bucket name — reader downloads segments from this bucket
    - secretKey: S3_BUCKET_NAME
      remoteRef:
        key: /zio-lucene/{{ .Values.env }}/s3/segments
