env: dev

image:
  repository: mattlangsenkamp/reader-server
  tag: latest
  pullPolicy: Always

serviceAccount:
  irsaRoleArn: ""  # run 'make update-irsa-values STACK=dev' after pulumi up

replicaCount: 1
