env: dev

image:
  repository: mattlangsenkamp/writer-server
  tag: latest
  pullPolicy: Always

storageClassName: gp2

serviceAccount:
  irsaRoleArn: arn:aws:iam::853236864732:role/writer-irsa-role-9278299

replicaCount: 1
